#!/bin/sh

CONTAINER_READY=`docker images | grep test_server | wc -l`
if [ $CONTAINER_READY = '0' ]
  then docker build -t test_server .
fi
docker run -it -v $(pwd)/notebooks/models:/opt/ml/models -p 5000:5000 test_server