#!/bin/sh

if [ $1 = '' ] 
  then IMAGE=rust_bert_notebook
  else IMAGE=$1
fi
CONTAINER_READY=$(docker images | grep $IMAGE | wc -l)
if [ $CONTAINER_READY = '0' ]
  then docker build -t $IMAGE .
fi
# checks for nvidia drivers
if command -v nvidia-smi &> /dev/null
  then GPU_ARG='--gpus all'
  else GPU_ARG=''
fi
docker run $GPU_ARG -it -v $(pwd)/:/opt/workspace -p 8888:8888 $IMAGE